name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        strict: high
        mypy-options: "--show-error-codes"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
    - uses: actions/upload-artifact@v2
      with:
        name: Result executable
        path: dist/windows
