name: Lint & CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd src && pip install -r requirements.txt
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: src
        strict: high
        mypy-options: "--show-error-codes"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - uses: actions/upload-artifact@v2
      with:
        name: Result executable
        path: src/dist/windows
